### ISSUE TITLE
Can ExpressAPR used in function-level APR tools?

### ISSUE THREAD

**Issue by Feng-Jay** [ExpressAPR/ExpressAPR#1]
Hi! This tool left a deep impression on me. you have done a great job!
But When I using this tool on testing function-level patches(which means the apr tool will generate a whole function, not a statement) it report following message in `result.jsonl`:

```bash
'message': 'java.lang.RuntimeException: patch not in a statement'}
```
and some correct patches are tagged as `T` timeout.

Is this tool can not used in this situation(function patches) or I can adjust its setting(such as time limit) to validate patches.

I'm hoping for a quick answer as this tool is critical to our operations.
Thanks. 😄

**Comment by Feng-Jay** [comment]
And here are more information in `result.jsonl` file:
```text
"RuntimeError(\"install instrumentation failed: 
{'stacktrace': ['expressapr.igniter.PreTransformer.normalizePatchedAstInBlock(PreTransformer.java:272)', 'expressapr.igniter.PreTransformer.preparePatches(PreTransformer.java:1140)', 'expressapr.igniter.PatchVerifier.verifyAllAndWriteFile(PatchVerifier.java:276)', 'expressapr.igniter.Main.generatePatchedClass(Main.java:105)', 'expressapr.igniter.Servant.respond(Servant.java:85)', 'expressapr.igniter.Servant.main(Servant.java:143)']
}\)
```

**Comment by xmcp** [comment]
ExpressAPR can be used for function-level APR. But you need to ensure that the `unpatched` area is within a method ***body***.

For example, this is invalid and will bring the `patch not in a statement` error you mentioned:

```json
{
  "context_above": "...",
  "unpatched": "void method(int arg) { stmt1(); while(x) {stmt2();} stmt3(); }",
  "context_below" : "...",
  ...
}
```

But this is valid:

```json
{
  "context_above": "... void method(int arg) {",
  "unpatched": "stmt1(); while(x) {stmt2();} stmt3();",
  "context_below" : "} ...",
  ...
}
```

**Comment by Feng-Jay** [comment]
OK, I understand！
Thank you for your prompt reply, and thank you again for your work. 🌞
